spring.application.name=spring-security.contact-management

spring.app.jwtSecretKey=7843hjkasdffhas27836y49hoiweufh123907rtg29bfou234pyrf7891gf4b134fb97f34bf
spring.app.jwtExpiration=300000

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.security=INFO
